#ifndef _ENUM_
#define _ENUM_

enum ghost_modes
{
    SCATTER,
    CHASE,
    FRIGHTENED,
};

enum moves
{
    UP,
    RIGHT,
    DOWN,
    LEFT
};

enum type
{
    PLAYER,
    GHOST,
    WALL,
    COIN,
    PORTAL
};

enum wall_type
{
    SHARPTOPLEFTCORNER,
    SHARPTOPRIGHTCORNER,
    SHARPBOTTOMLEFTCORNER,
    SHARPBOTTOMRIGHTCORNER,
    TOPRIGHTCORNERCONNECTOR,
    TOPLEFTCORNERCONNECTOR,
    TOPLEFTCORNERCONNECTORVERTICAL,
    TOPRIGHTCORNERCONNECTORVERTICAL,
    BOTTOMLEFTCORNERCONNECTORVERTICAL,
    BOTTOMRIGHTCORNERCONNECTORVERTICAL,
    TOPLEFTCORNERDOUBLE,
    TOPRIGHTCORNERDOUBLE,
    BOTTOMRIGHTCORNERDOUBLE,
    BOTTOMLEFTCORNERDOUBLE,
    TOPLEFTCORNERSINGLE,
    TOPRIGHTCORNERSINGLE,
    BOTTOMRIGHTCORNERSINGLE,
    BOTTOMLEFTCORNERSINGLE,
    TOPLEFTCORNERSINGLECONNECTOR,
    TOPRIGHTCORNERSINGLECONNECTOR,
    BOTTOMRIGHTCORNERSINGLECONNECTOR,
    BOTTOMLEFTCORNERSINGLECONNECTOR,
    STRAIGHTVERTICALLEFTDOUBLE,
    STRAIGHTVERTICALRIGHTDOUBLE,
    STRAIGHTVERTICALMIDDLELEFT,
    STRAIGHTVERTICALMIDDLERIGHT,
    STRAIGHTHORIZONTALTOPDOUBLE,
    STRAIGHTHORIZONTALBOTTOMDOUBLE,
    STRAIGHTHORIZONTALTOPSINGLE,
    STRAIGHTHORIZONTALBOTTOMSINGLE,
    FILLED,
};

enum pacman_animation_state
{
    OPEN,
    HALFWAY,
    CLOSED
};

#endif