#ifndef _ENUM_
#define _ENUM_

enum ghosts_types
{
    BLINKY,
    PINKY,
    INKY,
    CLYDE,
};

namespace characters
{
    enum game_characters
    {
        BLINKY,
        PINKY,
        INKY,
        CLYDE,
        PACMAN,
    };
}

enum ghost_modes
{
    SCATTER,
    CHASE,
    FRIGHTENED,
};

enum moves
{
    UP,
    RIGHT,
    DOWN,
    LEFT
};

enum type
{
    PLAYER,
    GHOST,
    WALL,
    COIN,
    PORTAL,
    POWER,
};

enum wall_type
{
    SHARPTOPLEFTCORNER,
    SHARPTOPRIGHTCORNER,
    SHARPBOTTOMLEFTCORNER,
    SHARPBOTTOMRIGHTCORNER,
    TOPRIGHTCORNERCONNECTOR,
    TOPLEFTCORNERCONNECTOR,
    TOPLEFTCORNERCONNECTORVERTICAL,
    TOPRIGHTCORNERCONNECTORVERTICAL,
    BOTTOMLEFTCORNERCONNECTORVERTICAL,
    BOTTOMRIGHTCORNERCONNECTORVERTICAL,
    TOPLEFTCORNERDOUBLE,
    TOPRIGHTCORNERDOUBLE,
    BOTTOMRIGHTCORNERDOUBLE,
    BOTTOMLEFTCORNERDOUBLE,
    TOPLEFTCORNERSINGLE,
    TOPRIGHTCORNERSINGLE,
    BOTTOMRIGHTCORNERSINGLE,
    BOTTOMLEFTCORNERSINGLE,
    TOPLEFTCORNERSINGLECONNECTOR,
    TOPRIGHTCORNERSINGLECONNECTOR,
    BOTTOMRIGHTCORNERSINGLECONNECTOR,
    BOTTOMLEFTCORNERSINGLECONNECTOR,
    STRAIGHTVERTICALLEFTDOUBLE,
    STRAIGHTVERTICALRIGHTDOUBLE,
    STRAIGHTVERTICALMIDDLELEFT,
    STRAIGHTVERTICALMIDDLERIGHT,
    STRAIGHTHORIZONTALTOPDOUBLE,
    STRAIGHTHORIZONTALBOTTOMDOUBLE,
    STRAIGHTHORIZONTALTOPSINGLE,
    STRAIGHTHORIZONTALBOTTOMSINGLE,
    FILLED,
    GATE,
};

enum pacman_animation_state
{
    OPEN,
    HALFWAY,
    CLOSED
};

enum power_types
{
    POWER_PELLET,
};

enum ghost_states
{
    DISABLED,
    ESCAPING,
    HEADING_BACK,
    FREE,
    SKIP_MOVE,
};

enum texture_surfaces
{
    HEADER,
    BODY,
    FOOTER,
};

enum game_states
{
    NO_MAP,
    PLAYING,
    EDITING,
    LOADING_MAP,
    LOADING_CONFIG,
    SELECTING_SIZE,
    SELECTING_CONFIG_NAME,
};

#endif